kind: Namespace
apiVersion: v1
metadata:
  name: shamitha-sh
  labels:
    name: shamitha-sh

---

apiVersion: v1
kind: Service
metadata:
  name: counter-service
  namespace: shamitha-sh
spec:
  selector:
    app: counter
  type: NodePort
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
    nodePort: 31032

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: partof-config
  namespace: shamitha-sh
  labels:
    app: config
data:
  PART_OF: CWiCS

---

apiVersion: v1
kind: Secret
metadata:
  name: identity-secret
  namespace: shamitha-sh
  labels:
    app: config
data:
  IDENTITY: c2hhbWl0aGEtc2g=

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: counter-pv
  labels:
    app: counter
  namespace: shamitha-sh
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: counter-deployment
  labels:
    app: counter
  namespace: shamitha-sh
spec:
  selector:
    matchLabels:
      app: counter
  template:
    metadata:
      labels:
        app: counter
    spec:
      containers:
      - name: counter
        image: ghcr.io/adyanth/docker-k8s-final-assessment:counter-latest
        env:
        - name: FILENAME
          value: "dump.txt"
        - name: IDENTITY
          valueFrom:
            secretKeyRef:
              name: identity-secret #the secret where it comes from
              key: IDENTITY
        - name: SERVE_PATH
          value: "count"
        - name: PART_OF
          valueFrom:
            configMapKeyRef:
              name: partof-config #the config map this value comes from
              key: PART_OF
        ports:
        - containerPort: 8080
        volumeMounts:
        - name: counter-storage
          mountPath: /data
      volumes:
      - name: counter-storage
        persistentVolumeClaim:
          claimName: counter-pv

